### ISSUE TITLE
Variation ", " is not supported by the property type 

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Deploy.Issues#8]
As described in https://github.com/umbraco/Umbraco.Cloud.Issues/issues/108 people are seeing errors while restoring content: `Variation "Variation "<null>,<null>" is not supported by the property type`.

We need to figure out how to replicate this specific error to be able to figure out what we can do about it.

---
_This item has been added to our backlog [AB#3253](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3253)_

---
_This item has been added to our backlog AB#38697_

**Comment by ronaldbarendse** [comment]
Believe it or not, but I've been able to reliably reproduce this error when using the Deploy export/import (and ignoring schema mismatches). Deploy will always include all property values in all culture and segment variations when creating a content artifact, but didn't check whether they were valid for the current document/property type configuration when setting those values again, causing the CMS to throw an exception for unsupported variations.

However, if the schema is the same between environments, you'd expect the CMS to only return property values for supported variations, but this doesn't always seem to be the case 😕 We've implemented a fix in the next Deploy minors (4.10, 10.4, 12.2 and 13.1, planned for release next Tuesday) that will explicitly check whether the variation is supported before trying to set the value. Any unsupported variations will now be logged as warnings, because we can't really do anything else (except ensure this doesn't error out the operation).

**Comment by pc-pdx** [comment]
Still experiencing this with  u17.5.0

> The source environment has thrown a Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException with message: The remote API has thrown an exception. It might have been caused by an inner System.NotSupportedException with message: Variation "en-US,<null>" is not supported by the property type.

Fortunately, the info found on this thread was enough to figure out that it was, eventually, a DB _thing_ and that I could simply duplicate the "offending" content and delete the original. This would avoid the pre-variant content not having the proper schema/structure(?) and allow a successful transfer onto the next environment.

**Comment by ronaldbarendse** [comment]
@pc-pdx Thanks for coming back with the details, and for the workaround you found. You are right that it comes down to something in the database, and it is not a schema mismatch between your environments: your document types are fine on both sides.

When a property type changes between invariant and "vary by culture", Umbraco deliberately leaves the existing rows in `umbracoPropertyData` untouched, so nothing is lost if you change the setting back. The CMS ignores those rows once their culture no longer matches the property type, but they are still loaded onto the content model. Deploy packs the property values exactly as it finds them, so those leftovers travel along in the artifact under a culture the property type no longer supports, and applying them on the receiving end is what raises the `NotSupportedException`.

The two messages in this thread are the same bug pointing in opposite directions: `"<null>,<null>"` is an invariant value left behind on a property that now varies by culture, and `"en-US,<null>"` (yours) is a culture value left behind on a property that is now invariant. It also explains why duplicating the node worked: the copy is written fresh, so it only gets rows for the variations the property type currently has.

This used to be handled. Deploy 4 through 13 skipped values whose variation the property type no longer supported and logged a warning instead of failing, and that guard was lost when the connectors were rewritten for Deploy 14, which is why 14 through 17 throw again. A fix to restore it is on its way, so the transfer completes and the orphaned values are skipped with a warning in the log.

Until that is released, your duplicate-and-delete approach works, and so does clearing the rows. This finds them in both directions (diagnostic only, it deletes nothing, and please take a backup first):

```sql
SELECT pd.id, pd.versionId, pt.Alias, pd.languageId, pd.segment, pt.variations
FROM umbracoPropertyData pd
INNER JOIN cmsPropertyType pt ON pt.id = pd.propertyTypeId
WHERE ((pt.variations & 1) = 1 AND pd.languageId IS NULL)      -- varies by culture, but the row has no language
   OR ((pt.variations & 1) = 0 AND pd.languageId IS NOT NULL)  -- invariant, but the row has a language
   OR ((pt.variations & 2) = 0 AND pd.segment IS NOT NULL)     -- does not vary by segment, but the row has a segment
```

The rows it returns hold values from before the variation change and are no longer used by the site, but they are still data, so back up before deleting anything.
